services:
  - type: web
    name: econexus-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://econexus-backend-0aa6.onrender.com/api # Cambia a la URL real de tu backend
